[env:hichi-wifi-v2]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

lib_deps = 
    knolleary/PubSubClient@^2.8

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=0

[env:hichi-wifi-v2-ota]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

lib_deps = 
    knolleary/PubSubClient@^2.8

monitor_speed = 115200
upload_protocol = espota
upload_port = hichi-brute-force.local
upload_flags = 
    --auth=brute123

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=0
